# Rust formatting configuration for IceGate
# https://rust-lang.github.io/rustfmt/

# Edition
edition = "2024"

# Ignore
ignore = [
    "crates/icegate-query/src/logql/antlr/",
    "!crates/icegate-query/src/logql/antlr/mod.rs",
    "!crates/icegate-query/src/logql/antlr/tests.rs",
    "!crates/icegate-query/src/logql/antlr/visitors.rs"
]

# Basic formatting
max_width = 120
chain_width = 80
reorder_imports = true

format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
