{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "icegate.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "icegate.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.migrate.enabled }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
{{- end }}
