global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: ingest
    metrics_path: /metrics
    static_configs:
      - targets: ["ingest:9091"]
  - job_name: query
    metrics_path: /metrics
    static_configs:
      - targets: ["query:9091"]
  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
